### ISSUE TITLE
Question about 'Delivery method'

### ISSUE THREAD

**Issue by sonnt2510** [kirill-zhirnov/boundless-nextjs-sample#87]
hi Kirill, i dont know why but the 'Delivery method' step in checkout page is gone from all of my sites, even though I already added Shipping method.
<img width="1314" alt="Screenshot 2023-12-13 at 9 44 03 AM" src="https://github.com/kirill-zhirnov/boundless-nextjs-ecommerce-template/assets/31029334/65e54202-5917-4bd6-ab98-e59908ffac65">
<img width="1008" alt="Screenshot 2023-12-13 at 9 47 45 AM" src="https://github.com/kirill-zhirnov/boundless-nextjs-ecommerce-template/assets/31029334/37ab0f34-4f16-4dff-82bb-a9e0b56fcd12">

**Comment by kirill-zhirnov** [comment]
Hi @sonnt2510 
Is the product physical? Check it here:
<img width="1501" alt="Снимок экрана 2023-12-13 в 08 29 52" src="https://github.com/kirill-zhirnov/boundless-nextjs-ecommerce-template/assets/1384581/8edc2faa-e1c9-43fe-aa08-2412e6a501c7">

**Comment by sonnt2510** [comment]
hi @kirill-zhirnov awesome, thanks mate, and is there anyway that I can customize the Shipping Address form just a little bit, like remove zip code, city, state ... or change the input label

**Comment by sonnt2510** [comment]
thanks @kirill-zhirnov i got it
